--- 
apiVersion: v1
kind: Service
metadata: 
  name: helloworld-services
spec: 
  ports: 
    - 
      port: 80
  protocol: TCP
  selector: 
    app: helloworld
  targertPort: nodejs-port
  type: LoadBalancer
