--- 
apiVersion: v1
kind: Service
metadata: 
  name: helloworld-services
spec: 
  ports: 
    - port: 80
  protocol: TCP
  targetPort: nodejs-port
  selector: 
    app: helloworld
  type: LoadBalancer
